C_FLAGS=-g -O0

all:
	$(CC) test.c $(C_FLAGS) -o test # -lhmalloc -L/Users/kammerdienerb/Documents/GitHub/hmalloc/lib
	$(CC) test_thr.c $(C_FLAGS) -o test_thr -lpthread # -lhmalloc -L/Users/kammerdienerb/Documents/GitHub/hmalloc/lib
	$(CXX) test_pp.cpp $(C_FLAGS) -o test_pp
